openapi: 3.1.0
info:
  title: API Game-score
  description: apagnan
  version: 0.0.1

servers:
- url: http://localhost:7777
  description: Serveur de développement

tags:
  - name: hello
    description: Première API avec Express
      
paths:
  /api/hello/world:
    get:
      tags:
        - hello
      description: Message de bienvenue
      responses:
        200:
          description: Retourne un message de bienvenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
  /api/hello/square/{number}:
    get:
      tags:
        - hello
      description: Calcule tah les carrés
      parameters:
        - name: number
          in: path
          description: Le nombre dont on veut calculer le carré
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Retourne un carré spécifié dans l'url
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Square'
  /api/hello:
    get:
      tags:
        - hello
      description: utilise la base de données
      responses:
        200:
          description: Retourne la liste des hello world
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
    post:
      tags:
        - hello
      description: Ajoute un nouveau hello
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hello'
      responses:
        201:
          description: Hello ajouté avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hello'
  
components:
  schemas:
    Hello:
      type: object
      properties:
        message:
          type: string
      additionalProperties: false
      required:
        - message
    Square:
      type: object
      properties:
        result:
          type: integer
        error:
          type: string
      additionalProperties: false
      required:
        - result